[package]
name = "rssql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rssql-macro = { path = "rssql-macro" }
tiberius = { version = "0.9.1", features = ["chrono"] }
serde_json = "1.0.99"
tokio = { version = "1.24.1", features = ["full"] }
tokio-util = { version = "0.7.4", features = ["full"] }
futures-lite = "1.12.0"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.71"
async-trait = "0.1.68"
